backend:
  name: github
  repo: DavidThorpe71/plant-site-two

media_folder: static/assets
public_folder: assets
media_library:
  name: cloudinary
  config:
    cloud_name: dykweel8h
    api_key: 852518696577879
    default_transformations:
      - - fetch_format: auto
          width: 600
          quality: auto

collections:
  - name: plants
    label: Plants
    folder: plants
    create: true
    identifier_field: name
    fields:
      - label: "Name"
        name: "name"
        widget: "string"
        required: true
      - label: "Image"
        name: "image"
        widget: "image"
        required: true
      - label: "Purchase date"
        name: "date"
        widget: "datetime"
        required: true
      - label: "Watering frequency"
        name: "waterFreq"
        widget: "select"
        options:
          [
            "Daily",
            "Weekly",
            "Every two weeks",
            "Once a month",
            "Less than once a month",
          ]
        required: false
      - label: "Light instructions"
        name: "lightInst"
        widget: "select"
        options:
          [
            "No light needed",
            "In the shade",
            "Indirect light",
            "By a window",
            "Direct light",
          ]
      - label: "Notes"
        name: "notes"
        widget: "text"
        required: false
